name: Pre-Release Checks

# Once the default branch for satijalab/seurat has been updated to from 
# `master` to `main` this workflow will be triggered on `workflow_dispatch`.
# Until then, we'll manually rebase this branch onto whatever branch
# we'd like to run the workflow against.
on:
  push:
    branches:
      - check/pre-release
    
# Runs a reverse dependency check similar to CRAN, for more details see 
# https://github.com/r-devel/recheck. 
jobs:
  check-reverse-dependencies:
    uses: r-devel/recheck/.github/workflows/recheck.yml@v1
    with:
      which: most
